version: '3'

services: 
    php:
        container_name: php
        image: php:8-fpm
        volumes:
            - $PWD/www:/srv

    caddy: 
        image: caddy:latest
        ports: 
            - 80:80
        volumes: 
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/www:/srv
            - caddy_data:/data
            - ./resolv.conf:/etc/resolv.conf
        restart: unless-stopped
        depends_on:
            - php
    
    xray:
        image: teddysun/xray
        ports:
            - 443:443/tcp
            - 443:443/udp
        volumes:
            - caddy_data:/data
            - .:/etc/xray
            - ./hosts:/etc/hosts
        restart: always
        depends_on:
            - caddy

volumes:
    caddy_data:
